### ISSUE TITLE
Parse or loading error on registering node

### ISSUE THREAD

**Issue by sosiouxme** [detiber/openshift-ansible#7]
Ran into the following error during my beta2 run... after installing master+node, went back and added two independent nodes. Only this part failed:

```
TASK: [openshift_node | Register node (if not already registered)] ************ 
ok: [master.osv3.example.com]
failed: [node2.osv3.example.com] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1426571836.41-200628100654096/openshift_register_node", line 1799, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1426571836.41-200628100654096/openshift_register_node", line 103, in main
    config = json.loads(output)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

failed: [node1.osv3.example.com] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1426571836.38-144895354006308/openshift_register_node", line 1799, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1426571836.38-144895354006308/openshift_register_node", line 103, in main
    config = json.loads(output)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Everything else seemed to go fine (of course, some bits skipped without this working). The files mentioned don't appear to exist. Not sure what info to attach, suggestions welcome... here is the hosts file for reference, didn't change anything else.

```
# cat /etc/ansible/hosts 
# This is an example of a bring your own (byo) host inventory

# host group for masters
[masters]
master.osv3.example.com

# host group for nodes
[nodes]
master.osv3.example.com
node[1:2].osv3.example.com
```

**Comment by sosiouxme** [comment]
This was almost certainly due to the hostname not being a FQDN (instead what our IaaS inserted; OpenStack/EC2 would likely see this problem). hostname -f would fail on these hosts. It worked once I set the hostnames to node{1,2}.osv3.example.com.

**Comment by detiber** [comment]
@sosiouxme Indeed, the byo playbooks do not take into account cloud type deployments (yet).

While I haven't tested it yet, updating your inventory as follows should do the trick:

```
# host group for masters
[masters]
master.osv3.example.com

# host group for nodes
[nodes]
master.osv3.example.com openshift_hostname_workaround=true openshift_public_ip=<ip address>
node[1:2].osv3.example.com openshift_hostname_workaround=true openshift_public_ip=<ip address>
```

**Comment by detiber** [comment]
@sosiouxme I don't believe this is an issue anymore with the latest v3-beta3, please re-open if you are still hitting this.
